spring.application.name=security_oauth

spring.security.oauth2.client.registration.google.client-id=207587068203-rmjb1us1v420um4h8gsv8iueeiaailek.apps.googleusercontent.com
spring.security.oauth2.client.registration.google.client-secret=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
spring.security.oauth2.client.registration.google.scope=profile,email